{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-demo.serviceAccountName" . }}
  labels:
    {{- include "app-demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   labels:
#     app.kubernetes.io/instance: demo-app-argocd
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: app-demo
#     app.kubernetes.io/version: 1.16.0
#     helm.sh/chart: app-demo-0.1.0
#   name: demo-app-argocd-app-demo
#   namespace: demo
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     - PruneLast=true

#     automated:
#       selfHeal: true
#       prune: true
